---

services:
  app:
    build:
      context: .
    volumes:
      - ./:/build
      - ./core/build/devkit/extras/config/database.json:/build/config/database.json
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      flare_network:
        aliases:
          - rpc-machines.flarehotspot-dev.com

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flarehotspot  # Customize database name as needed
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 30
    networks:
      flare_network:

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pg.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      flare_network:

  # mariadb:
  #   image: mariadb:latest
  #   volumes:
  #     - mariadb:/var/lib/mysql
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=root
  #   healthcheck:
  #     test: mariadb-admin ping -h 127.0.0.1 --password=root
  #     start_period: 20s
  #     start_interval: 1s
  #     interval: 30s
  #     timeout: 5s
  #     retries: 30
  #   networks:
  #     flare_network:

  # phpmyadmin:
  #   image: phpmyadmin
  #   volumes:
  #     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  #   ports:
  #     - 8081:80
  #   depends_on:
  #     - mariadb
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mariadb
  #     - PMA_USER=root
  #     - PMA_PASSWORD=root
  #   networks:
  #     flare_network:

volumes:
  postgres:

networks:
  flare_network:
    external: true
